ImmigrationApp/Controllers/CandidateController.cs
using ImmigrationApp.Currentuser;
using ImmigrationApp.Data;
using ImmigrationApp.Models;
using LinqKit;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ImmigrationApp.Controllers
{
    public class CandidateController : Controller
    {
        public ApplicationDbContext _db { get; set; }
        public ICurrentuser _Currentuser { get; set; }
        private readonly IWebHostEnvironment host;
        public CandidateController(ApplicationDbContext db, ICurrentuser Currentuser, IWebHostEnvironment host)
        {
            _Currentuser = Currentuser;
            _db = db;
            this.host = host;
        }
        [Route("/Candidate/Profile")]
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var CanidateInfo = await _db.CustomResume
                .Include(x=>x.ResumeEducationList)
                .Include(x=>x.ResumeExperienceList)
                .Include(x=>x.ResumeSkillChildList)
                .Include(x=>x.ResumeLanguageChildList)
                .Include(x=>x.ResumeLinkChildList)
                .SingleOrDefaultAsync(x=>x.UserId == _Currentuser.GetUserId());
            var Skills = await _db.Skill.ToListAsync();
            IEnumerable<SelectListItem> Country = _db.Country.OrderBy(x=>x.CountryName).Select(c => new SelectListItem
            {
                Value = c.CountryName,
                Text = c.CountryName,
                Selected = CanidateInfo.Country == c.CountryName
            });
            var VM = new CanidateVM
            {
                CustomResume = CanidateInfo,
                CountryList = Country,
                SkillList = Skills,
            };
            return View(VM);
        }
        [AllowAnonymous]
        [Route("/Candidate/Profile-View/{Slugname}/{CallBy}")]
        [HttpGet]
        public async Task<IActionResult> ProfileView(string Slugname ,string CallBy)
        {
            var CanidateInfo = await _db.CustomResume
                .Include(x=>x.ResumeEducationList)
                .Include(x=>x.ResumeExperienceList)
                .Include(x=>x.ResumeSkillChildList)
                .Include(x=>x.ResumeLanguageChildList)
                .Include(x=>x.ResumeLinkChildList)
                .SingleOrDefaultAsync(x=>x.CallBy == CallBy);
            var VM = new CanidateVM
            {
                CustomResume = CanidateInfo,
            };
            return View(VM);
        }
        [AllowAnonymous]
        [Route("/Candidate/Browse-Candidate")]
        [HttpGet]
        public async Task<IActionResult> BrowseCandidate()
        {
            var CanidateInfo = await _db.CustomResume
                .Include(x=>x.ResumeEducationList)
                .Include(x=>x.ResumeExperienceList)
                .Include(x=>x.ResumeSkillChildList)
                .Include(x=>x.ResumeLanguageChildList)
                .Include(x=>x.ResumeLinkChildList)
                .Include(x=>x.User)
                .ToListAsync();
            var VM = new CanidateVM
            {
                CustomResumeList = CanidateInfo,
            };
            return View(VM);
        }
        [AllowAnonymous]
        [Obsolete]
        public async Task<JsonResult> searchcanidate(SearchcanidateDTO SearchcanidateDTO)
        {
            var predicate = PredicateBuilder.True<CustomResume>();

            //if (!string.IsNullOrEmpty(SearchcanidateDTO.keyword))
            //{
            //    predicate = predicate.And(c => c.FirstName.Contains(SearchcanidateDTO.keyword));
            //}
            //if (!string.IsNullOrEmpty(SearchcanidateDTO.keyword))
            //{
            //    predicate = predicate.And(c => c.LastName.Contains(SearchcanidateDTO.keyword));
            //}
            if (!string.IsNullOrEmpty(SearchcanidateDTO.keyword))
            {
                predicate = predicate.And(c => c.Headline.Contains(SearchcanidateDTO.keyword));
            }
            if (!string.IsNullOrEmpty(SearchcanidateDTO.address))
            {
                predicate = predicate.And(c => c.Street.Contains(SearchcanidateDTO.address));
            }
            //
            var canidateInfo = await _db.CustomResume.Where(predicate)
                .Include(x => x.ResumeEducationList)
                .Include(x => x.ResumeExperienceList)
                .Include(x => x.ResumeSkillChildList)
                .Include(x => x.ResumeLanguageChildList)
                .Include(x => x.ResumeLinkChildList)
                .ToListAsync();
            return Json(canidateInfo);
        }
        [HttpPost]
        public async Task<JsonResult> Update(IFormCollection form)
        {
            var Request = form["candidaterequest"];
            var CustomResume = JsonConvert.DeserializeObject<CustomResume>(Request);
            //
            Random r = new Random();
            int num = r.Next();
            var webrootpath = host.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            string Username = await _db.User.Where(x=>x.Id.Equals(_Currentuser.GetUserId())).Select(x => x.FirstName).FirstOrDefaultAsync();
            //Image Insert
            if (files.Count > 0)
            {
                var uploads = Path.Combine(webrootpath, "Upload");
                var Ext = Path.GetExtension(files[0].FileName);
                using (var stream = new FileStream(Path.Combine(uploads, $"{Username}_{num}_{Ext}"), FileMode.Create))
                {
                    files[0].CopyTo(stream);
                }
                CustomResume.ResumeUrlPath = $"{Username}_{num}_{Ext}";
            }
            var Sk = await _db.ResumeSkillChild.Where(x => x.CustomResumeId == CustomResume.Id).ToListAsync();
            var skill = await _db.Skill.Select(x=>x.NormalizedName).ToListAsync();
            foreach (var item in Sk)
            {
                var ch = skill.Any(c => c == item.SkillName.ToUpper());
                if (!ch)
                {
                    var addskill = new Skill();
                    addskill.Name = item.SkillName;
                    addskill.NormalizedName = item.SkillName.ToUpper();
                    await _db.Skill.AddAsync(addskill);
                }
            }
            var check = await _db.JobSubCategory.Where(x => x.Name.Contains(CustomResume.Headline)).CountAsync();
            if (check == 0)
            {
                var subcat = new JobSubCategory();
                subcat.Id = 0;
                subcat.JobMainCategoryId = Convert.ToInt64(519);
                subcat.Name = CustomResume.Headline;
                await _db.JobSubCategory.AddAsync(subcat);
            }
            _db.ResumeExperience.RemoveRange(await _db.ResumeExperience.Where(x => x.CustomResumeId == CustomResume.Id).ToListAsync());
            _db.ResumeEducation.RemoveRange(await _db.ResumeEducation.Where(x => x.CustomResumeId == CustomResume.Id).ToListAsync());
            _db.ResumeSkillChild.RemoveRange(Sk);
            _db.ResumeLanguageChild.RemoveRange(await _db.ResumeLanguageChild.Where(x => x.CustomResumeId == CustomResume.Id).ToListAsync());
            _db.ResumeLinkChild.RemoveRange(await _db.ResumeLinkChild.Where(x => x.CustomResumeId == CustomResume.Id).ToListAsync());
            //
            string slugname = CustomResume.FirstName + ' ' + CustomResume.LastName;
            CustomResume.SlugName = slugname.Replace(" ", "-");
            _db.CustomResume.Update(CustomResume);
            await _db.SaveChangesAsync();
            return Json("Updated Successfully");
        }
        [HttpGet]
        [Route("/Candidate/GetSkill")]
        public async Task<JsonResult> GetSkill(string term)
        {
            term = term.ToUpper();
            var Skills = await _db.Skill.Where(c=>c.NormalizedName.Contains(term)).Distinct().ToListAsync();
            return Json(Skills);
        }
        [AllowAnonymous]
        [HttpGet]
        [Route("/Candidate/GetCategory")]
        public async Task<JsonResult> GetCategory(string term)
        {
            var Category = await _db.JobSubCategory.Where(c=>c.Name.Contains(term)).Distinct().ToListAsync();
            var data = await _db.Job.Where(c => c.Title.Contains(term)).Distinct().ToListAsync();
            return Json(new { Category = Category ,title =data});
        }
    }
}

ImmigrationApp/Views/Candidate/BrowseCandidate.cshtml
@model CanidateVM
@{
    ViewData["Title"] = "BrowseCandidate";
}
<style>
    .main-comment {
        font-size: 14px;
        padding: 30px 0 0 0px;
        position: relative;
    }
</style>
<!-- Header Area Start -->
<partial name="_headerwhite" />
<!-- Header Area End -->
<!-- Breadcromb Area Start -->
<section class="jobguru-breadcromb-area">
    <div class="breadcromb-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcromb-box-pagin">
                        <ul>
                            <li><a href="#">home</a></li>
                            <li><a href="#">Candidates</a></li>
                            <li class="active-breadcromb"><a href="#">Browse Candidates</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcromb Area End -->
<!-- Top Job Area Start -->
<section class="jobguru-top-job-area browse-page section_70">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-3 mx-auto">
                <div class="job-grid-sidebar">
                    <!-- Single Job Sidebar Start -->
                    <div class="single-job-sidebar sidebar-location">
                        <h3>location</h3>
                        <div class="job-sidebar-box">
                                <p>
                                    <input type="text" id="address" placeholder="Location">
                                </p>
                        </div>
                    </div>
                    <!-- Single Job Sidebar End -->
                   
                    <!-- Single Job Sidebar Start -->
                    <div class="single-job-sidebar sidebar-category">
                        <h3>Category</h3>
                        <div class="job-sidebar-box">
                                <select class="sidebar-category-select-2" id="category">
                                    <option value="1">any category</option>
                                    <option value="2">accounting/finance</option>
                                    <option value="3">automotive jobs</option>
                                    <option value="4">construction</option>
                                    <option value="5">design, art & multimedia</option>
                                    <option value="6">education training</option>
                                    <option value="7">restaurent/food</option>
                                    <option value="7">programming/tech</option>
                                    <option value="7">sales/marketing</option>
                                    <option value="7">data science/analysis</option>
                                </select>
                        </div>
                    </div>
                    <!-- Single Job Sidebar End -->
                </div>
            </div>
            <div class="col-md-12 col-lg-9  mx-auto">
                <div class="job-grid-right">
                    <div class="browse-job-head-option">
                        <div class="job-browse-search">
                            <form action="#">
                                <input type="text" name="keywords" id="keyword" placeholder="Search candidate Here...">
                                <button type="button" onclick="search();"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                    <!-- end job head -->
                    <div class="candidate-list-page">
                        @{
                            foreach (var item in Model.CustomResumeList)
                            {
                                <div class="single-candidate-list">
                                    <div class="main-comment">
                                        <div class="candidate-text">
                                            <div class="candidate-info">
                                                <div class="candidate-title">
                                                    <h3><a asp-action="ProfileView" asp-controller="Candidate" asp-route-slugname="@item.SlugName" asp-route-CallBy="@item.CallBy">@item.FirstName @item.LastName (@item.Headline)</a></h3>
                                                </div>
                                            </div>
                                            <div class="candidate-text-inner">
                                                <p>@Html.Raw(item.Summary)</p>
                                            </div>
                                            <div class="candidate-text-bottom">
                                                <div class="candidate-text-box">
                                                    <p class="company-state"><i class="fa fa-map-marker"></i> @item.City</p>
                                                    @*<p class="varify"><i class="fa fa-check"></i> $0 / hr</p>*@
                                                </div>
                                                <div class="candidate-action">
                                                    <a asp-action="ProfileView" asp-controller="Candidate" asp-route-slugname="@item.SlugName" asp-route-CallBy="@item.CallBy" class="jobguru-btn-2">view profile</a>
                                                    <a asp-route-ConnectionId="@item.UserId" asp-action="CreatePeopleHub" asp-controller="ChatApp" class="jobguru-btn-2">Send message</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                    @*<div class="pagination-box-row">
                        <p>Page 1 of 6</p>
                        <ul class="pagination">
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li>...</li>
                            <li><a href="#">6</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                        </ul>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Top Job Area End -->
<script src="/js/canfind.js" asp-append-version="true"></script>

ImmigrationApp/Views/Candidate/ProfileView.cshtml
@model CanidateVM
@{
    ViewData["Title"] = "Profile-View";
    string path = "<a href='#' >Check Resume</a>";
    if (Model.CustomResume.ResumeUrlPath != "")
    {
        path = "<a href='/Upload/"+ Model.CustomResume.ResumeUrlPath + "' target='_blank'>Check Resume</a>";
    }
}
<style>
    .main-comment {
        font-size: 14px;
        padding: 30px 0 0 0px;
        position: relative;
    }
</style>
<!-- Header Area Start -->
<partial name="_headerwhite" />
<!-- Header Area End -->
<!-- Single Candidate Start -->
<section class="single-candidate-page section_70">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="single-candidate-box">
                    <div class="single-candidate-box-right">
                        <h4>@Model.CustomResume.FirstName @Model.CustomResume.LastName</h4>
                        <p>@Model.CustomResume.Headline</p>
                        @*<div class="single-candidate-rate">
                            <p class="rating-company">4.9</p>
                            <ul>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star-half-o"></i></li>
                            </ul>
                        </div>*@
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="single-candidate-action">
                    <a href="#" class="bookmarks"><i class="fa fa-star"></i>Bookmarks</a>
                    <a asp-route-ConnectionId="@Model.CustomResume.UserId" asp-action="CreatePeopleHub" asp-controller="ChatApp" class="candidate-contact"><i class="fa fa-envelope"></i>send message</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Single Candidate End -->
<!-- Single Candidate Bottom Start -->
<div class="single-candidate-bottom-area section_70">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-9 mx-auto">
                <div class="single-candidate-bottom-left">
                    <div class="single-candidate-widget">
                        <h3>About Me</h3>
                        @Html.Raw(Model.CustomResume.Summary)
                    </div>
                    <div class="single-candidate-widget">
                        <h3>Skills</h3>
                        <ul>
                            @foreach (var item in Model.CustomResume.ResumeSkillChildList)
                            {
                                <li><a href="#">@item.SkillName</a></li>
                            }
                        </ul>
                    </div>
                    
                    <div class="single-candidate-widget">
                        <h3>work History</h3>
                        @foreach (var item in Model.CustomResume.ResumeExperienceList)
                        {
                            <div class="single-work-history">
                                <div class="single-candidate-list">
                                    <div class="main-comment">
                                        <div class="candidate-text">
                                            <div class="candidate-info">
                                                <div class="candidate-title">
                                                    <h3><a href="#">@item.Company</a></h3>
                                                </div>
                                                <p><i class="fa fa-calendar-check-o"></i>
                                                @item.FromMonth @item.FromYear -
                                                @{ 
                                                    if (item.CurrentlyEnrolled == true)
                                                    {
                                                        <span>Present</span>
                                                    }
                                                    else
                                                    {
                                                        <span>@item.ToMonth @item.ToYear</span>
                                                    }
                                                }
                                                
                                                </p>
                                            </div>
                                            <div class="candidate-text-inner">
                                                @Html.Raw(item.Description)
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        
                    </div>
                    <div class="single-candidate-widget">
                        <h3>education History</h3>
                        @foreach (var item in Model.CustomResume.ResumeEducationList)
                        {
                            <div class="single-work-history">
                                <div class="single-candidate-list">
                                    <div class="main-comment">
                                        <div class="candidate-text">
                                            <div class="candidate-info">
                                                <div class="candidate-title">
                                                    <h3><a href="#">@item.SchoolName - @item.LevelofEducation in @item.FieldofStudy</a></h3>
                                                </div>
                                                <p><i class="fa fa-calendar-check-o"></i>
                                                @item.FromMonth @item.FromYear -
                                                @{ 
                                                    if (item.CurrentlyEnrolled == true)
                                                    {
                                                        <span>Present</span>
                                                    }
                                                    else
                                                    {
                                                        <span>@item.ToMonth @item.ToYear</span>
                                                    }
                                                }
                                                
                                                </p>
                                            </div>
                                            @*<div class="candidate-text-inner">
                                                @Html.Raw(item.Description)
                                            </div>*@
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        
                    </div>
                </div>
            </div>
            <div class="col-md-10 col-lg-3 mx-auto">
                <div class="single-candidate-bottom-right">
                    <div class="single-candidate-widget-2">
                        <a href="#" class="jobguru-btn-2">
                            <i class="fa fa-info-circle"></i>
                            candidate info
                        </a>
                    </div>
                    <div class="single-candidate-widget-2">
                        <ul>
                            <li><i class="fa fa-envelope"></i> @Model.CustomResume.Email</li>
                            <li><i class="fa fa-phone"></i> @Model.CustomResume.PhoneNumber</li>
                            <li><i class="fa fa-reddit-square"></i> @Html.Raw(path)</li>
                        </ul>
                    </div>
                    @*<div class="single-candidate-widget-2">
                        <h3>Social Links</h3>
                        <ul class="candidate-social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>*@
                    @*<div class="single-candidate-widget-2">
                        <h3>Quick Contacts</h3>
                        <form>
                            <p>
                                <input type="text" placeholder="Your Name">
                            </p>
                            <p>
                                <input type="email" placeholder="Your Email Address">
                            </p>
                            <p>
                                <textarea placeholder="Write here your message"></textarea>
                            </p>
                            <p>
                                <button type="submit">Send Message</button>
                            </p>
                        </form>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Single Candidate Bottom End -->