ImmigrationApp/Controllers/EmployerController.cs
using ImmigrationApp.Currentuser;
using ImmigrationApp.Data;
using ImmigrationApp.Models;
using ImmigrationApp.Repositries;
using ImmigrationApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
namespace ImmigrationApp.Controllers
{
    public class EmployerController : BaseController
    {
        public ApplicationDbContext _db { get; set; }
        public ICompanyInfoServices _companyInfoservice { get; set; }
        public ICommonRepo _CommonRepo { get; set; }
        public ICompanyInfoRepo _companyInfo { get; set; }
        public ICurrentuser _Currentuser { get; set; }
        private readonly IWebHostEnvironment host;
        public EmployerController(ICompanyInfoRepo companyInfos, ApplicationDbContext db, ICommonRepo CommonRepo, ICurrentuser Currentuser, ICompanyInfoServices companyInfo, IWebHostEnvironment host)
        {
            _db = db;
            _companyInfo = companyInfos;
            _companyInfoservice = companyInfo;
            _CommonRepo = CommonRepo;
            _Currentuser = Currentuser;
            this.host = host;
        }
        [Route("/Employer/Dashboard")]
        [HttpGet]
        public async Task<IActionResult> Dashboard()
        {
            var CompanyInfo = await _companyInfo.GetSingleCompanyInfo(_Currentuser.GetUserId());
            return View(CompanyInfo);
        }
        [Route("/Employer/Profile")]
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var CompanyInfo = await _companyInfo.GetSingleCompanyInfo(_Currentuser.GetUserId());
            var Country =  _CommonRepo.GetCountryList(CompanyInfo.Country);
            IEnumerable<SelectListItem> Category = _db.JobMainCategory.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name,
            });
            var VM = new CompanyInfoVM
            {
                CompanyInfo=CompanyInfo,
                CountryList=Country,
                JobMainCategoryList=Category
            };
            return View(VM);
        }
        [AllowAnonymous]
        [Route("/Company/Profile-View/{Slugname}/{CallBy}")]
        [HttpGet]
        public async Task<IActionResult> ViewProfile(string Slugname,string CallBy)
        {
            var CompanyInfo = await _companyInfo.GetCompanyInfoByslugName(CallBy);
            return View(CompanyInfo);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateProfile(CompanyInfo CompanyInfo)
        {
            Random r = new Random();
            int num = r.Next();
            var webrootpath = host.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            //Image Insert
            if (files.Count > 0)
            {
                var uploads = Path.Combine(webrootpath, "Upload");
                var Ext = Path.GetExtension(files[0].FileName);
                using (var stream = new FileStream(Path.Combine(uploads, num + Ext), FileMode.Create))
                {
                    files[0].CopyTo(stream);
                }
                CompanyInfo.LogoPath = num + Ext;
            }
            string Slugname = CompanyInfo.Company;
            CompanyInfo.SlugName = Slugname.Replace(" ", "-");
            _db.CompanyInfo.Update(CompanyInfo);
            await _db.SaveChangesAsync();
            AddNotificationToView("Company Profile Updated Successfully", true);
            return RedirectToAction("Profile");
        }
        [Route("/Employer/Manage-Job-Request")]
        public IActionResult ManageRequest()
        {
            var AppliedJob = (from x in _db.ApplyforJob
                              select new ApplyforJob
                              {
                                  Id = x.Id,
                                  JobId = x.JobId,
                                  CanidateId = x.CanidateId,
                                  EmployerId = x.EmployerId,
                                  CoverLetter = x.CoverLetter,
                                  AppliedUsing = x.AppliedUsing,
                                  AppliedDate = x.AppliedDate,
                                  Status = x.Status,
                                  myuser = _db.User.FirstOrDefault(z => z.Id == x.CanidateId),
                                  mycustomresume = _db.CustomResume.FirstOrDefault(z => z.UserId == x.CanidateId),
                                  myJob = _db.Job.FirstOrDefault(z => z.Id == x.JobId),
                              }).ToList();
            return View(AppliedJob);
        }
    }
}

ImmigrationApp/Controllers/FindJobController.cs
using ImmigrationApp.Currentuser;
using ImmigrationApp.Data;
using ImmigrationApp.Models;
using LinqKit;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImmigrationApp.Controllers
{
    public class FindJobController : BaseController
    {
        private ApplicationDbContext _db { get; set; }
        private ICurrentuser _Cur { get; set; }
        
        public FindJobController(ICurrentuser Cur, ApplicationDbContext db)
        {
            _db = db;
            _Cur = Cur;
        }
        [AllowAnonymous]
        [Route("/Find-a-job/{Alpha}")]
        public async Task<IActionResult> JobFind()
        {
              var JobList = await (from x in _db.Job
                                 select new JobDTO
                                 {
                                     Id = x.Id,
                                     logoPath = _db.CompanyInfo.Where(c => c.Id.Equals(x.CompanyInfoId)).Select(a => a.LogoPath).FirstOrDefault(),
                                     Title = x.Title,
                                     SpecificAddress = x.SpecificAddress,
                                     Street = x.Street,
                                     City = x.City,
                                     Province = x.Province,
                                     PostalCode = x.PostalCode,
                                     AddressToAdvertise = x.AddressToAdvertise,
                                     ShowBy = x.ShowPayby,
                                     MinPay = x.MinPay,
                                     MaxPay = x.MaxPay,
                                     Amount = x.Amount,
                                     Rate = x.Rate,
                                     SlugName = x.SlugName,
                                     PostDateTime = x.PostDateTime,
                                     CallBy=x.CallBy
                                 }).ToListAsync();
            var VM = new SearchjobVM
            {
                JobDTOList = JobList,
                JobTypeList = await _db.JobType.ToListAsync(),
                HomeDTO = new HomeDTO(),
            };
            return View(VM);
        }
        //
        [AllowAnonymous]
        [Route("/Find-a-jobs/{Key}")]
        [Obsolete]
        public async Task<IActionResult> JobFinds(HomeDTO HomeDTO, string Key)
        {
            var JobList = new List<JobDTO>();
            if (HomeDTO != null)
            {
                var predicate = PredicateBuilder.True<Job>();
                if (!string.IsNullOrEmpty(HomeDTO.citystate))
                {
                    predicate = predicate.And(c => c.Street.Contains(HomeDTO.citystate));
                }
                if (!string.IsNullOrEmpty(HomeDTO.category))
                {
                    predicate = predicate.And(c => c.Title.Contains(HomeDTO.category));
                }
                //if (!string.IsNullOrEmpty(HomeDTO.category))
                //{
                //    predicate = predicate.Or(c => c.JobSubCategoryId.ToString().Contains(HomeDTO.category));
                //}
                var firstlist = await _db.Job.Where(predicate).ToListAsync();
                foreach (var x in firstlist)
                {
                    JobList.Add(new JobDTO
                    {
                        Id = x.Id,
                        logoPath = _db.CompanyInfo.Where(z => z.Id.Equals(x.CompanyInfoId)).Select(z => z.LogoPath).FirstOrDefault(),
                        Title = x.Title,
                        SpecificAddress = x.SpecificAddress,
                        Street = x.Street,
                        City = x.City,
                        Province = x.Province,
                        PostalCode = x.PostalCode,
                        AddressToAdvertise = x.AddressToAdvertise,
                        ShowBy = x.ShowPayby,
                        MinPay = x.MinPay,
                        MaxPay = x.MaxPay,
                        Amount = x.Amount,
                        Rate = x.Rate,
                        SlugName = x.SlugName,
                        PostDateTime = x.PostDateTime,
                        CallBy = x.CallBy
                    });
                }
            }
            else
            {
                JobList = await (from x in _db.Job
                                 select new JobDTO
                                 {
                                     Id = x.Id,
                                     logoPath = _db.CompanyInfo.Where(c => c.Id.Equals(x.CompanyInfoId)).Select(a => a.LogoPath).FirstOrDefault(),
                                     Title = x.Title,
                                     SpecificAddress = x.SpecificAddress,
                                     Street = x.Street,
                                     City = x.City,
                                     Province = x.Province,
                                     PostalCode = x.PostalCode,
                                     AddressToAdvertise = x.AddressToAdvertise,
                                     ShowBy = x.ShowPayby,
                                     MinPay = x.MinPay,
                                     MaxPay = x.MaxPay,
                                     Amount = x.Amount,
                                     Rate = x.Rate,
                                     SlugName = x.SlugName,
                                     PostDateTime = x.PostDateTime,
                                     CallBy = x.CallBy
                                 }).ToListAsync();
            }
            var VM = new SearchjobVM
            {
                JobDTOList = JobList,
                JobTypeList = await _db.JobType.ToListAsync(),
                HomeDTO = HomeDTO,
                Key = Key
            };
            return View("JobFind", VM);
        }
        //
        [AllowAnonymous]
        [Obsolete]
        public async Task<JsonResult> searchjob(SearchDTO SearchDTO)
        {
            var predicate = PredicateBuilder.True<Job>();
            
            if (!string.IsNullOrEmpty(SearchDTO.Title))
            {
                predicate = predicate.And(c => c.Title.Contains(SearchDTO.Title));
            }
            if (!string.IsNullOrEmpty(SearchDTO.address))
            {
                predicate = predicate.And(c => c.Street.Contains(SearchDTO.address));
            }
            if (SearchDTO.category != null && SearchDTO.category !=0)
            {
                predicate = predicate.And(c => c.JobSubCategoryId.Equals(SearchDTO.category));
            }

            if (SearchDTO.types != null)
            {
                string[] _type = new string[] { };
                foreach (var type in SearchDTO.types)
                {
                    if (!string.IsNullOrEmpty(type.ToString()))
                    {
                        _type = _type.Concat(new string[] { type.ToString() }).ToArray();
                    }
                }
                predicate = predicate.And(c => c.JobTypeChildList.Any(z => _type.Contains(z.JobTypeId.ToString())));
            }
            var firstlist = await _db.Job.Where(predicate).ToListAsync();
            
            var JobList = new List<JobDTO>();
            foreach (var x in firstlist)
          {
                JobList.Add(new JobDTO
                {
                    Id =x.Id,
                    logoPath =_db.CompanyInfo.Where(z=>z.Id.Equals(x.CompanyInfoId)).Select(z=>z.LogoPath).FirstOrDefault(),
                    Title = x.Title,
                    SpecificAddress = x.SpecificAddress,
                    Street = x.Street,
                    City = x.City,
                    Province = x.Province,
                    PostalCode = x.PostalCode,
                    AddressToAdvertise = x.AddressToAdvertise,
                    ShowBy = x.ShowPayby,
                    MinPay = x.MinPay,
                    MaxPay = x.MaxPay,
                    Amount = x.Amount,
                    Rate = x.Rate,
                    SlugName = x.SlugName,
                    PostDateTime = x.PostDateTime,
                    CallBy = x.CallBy
                });
            }
            return Json(JobList);
        }
        [Route("/Apply-for-job/{slugname}/{Id}")]
        public async Task<IActionResult> JobApply(string slugname,long Id)
        {
            var user = await _db.User.SingleOrDefaultAsync(x=>x.Id== _Cur.GetUserId());
            var Job = new Job();
            string url = "";
            long canidateId = _Cur.GetUserId();
            if (user.Type == "Candidate")
            {
                Job = await _db.Job.SingleOrDefaultAsync(x => x.Id == Id);
                url = "/Candidate/Profile-View/" + await _db.CustomResume.Where(x => x.UserId == _Cur.GetUserId()).Select(x => x.SlugName).FirstOrDefaultAsync();
            }
            else 
            {
                user = new User();
            }
            var VM = new JobApplyVM 
            {
                user=user,
                Job=Job,
                ApplyforJob=new ApplyforJob(),
                url=url,
                canidateId= canidateId,
            };
            return View(VM);
        }
        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> ApplyforJob(ApplyforJob ApplyforJob)
        {
            ApplyforJob.Status = "Pending";
            ApplyforJob.AppliedDate = DateTime.Now;
            await _db.ApplyforJob.AddAsync(ApplyforJob);
            await _db.SaveChangesAsync();
            AddNotificationToView("Applied For Job Successfully",true);
            return RedirectToAction("Index","Home");
        }
        
        public async Task<IActionResult> Getstatus(string term)
        {
            string url = "";

ImmigrationApp/Views/Shared/_header.cshtml
@{
    //Sign In Check
    var userName = "";
    var user = new User();
    var isSignedIn = SignInManager.IsSignedIn(User);
    if (isSignedIn)
    {
        var userId = _currentuser.GetUserId();
        user = await _db.User.SingleOrDefaultAsync(c => c.Id.Equals(userId));
        //
        userName = "" + user.FirstName.Substring(0, 1) + "" + user.LastName?.Substring(0, 1) + "";
    }
 }
<header class="jobguru-header-area stick-top forsticky">
    <div class="menu-animation">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2">
                    <div class="site-logo">
                        <a asp-action="Index" asp-controller="Home">
                            <img src="/Front/assets/img/logo.png" alt="jobguru" class="non-stick-logo" />
                            <img src="/Front/assets/img/logo-2.png" alt="jobguru" class="stick-logo" />
                        </a>
                    </div>
                    <!-- Responsive Menu Start -->
                    <div class="jobguru-responsive-menu"></div>
                    <!-- Responsive Menu Start -->
                </div>
                <div class="col-lg-6">
                    <div class="header-menu">
                        <nav id="navigation">
                            <ul id="jobguru_navigation">

                                <li><a asp-action="JobFind" asp-controller="FindJob" asp-route-Alpha="ScokTCWcgLjzLxrUzuUbvHTbOchVBQFggmxnskcILSzqzzczAbKoHGFzdCKptziwbmPVlqHhKQfGlQBeWZOXMRLaXykViWmczdNzmkQlJqLhkgRrTsazHoZPsyVIejTq">Find Jobs</a></li>
                                <li><a asp-action="Companies" asp-controller="Home">Companies</a></li>
                                <li><a href="#">Salary Guide</a></li>
                                <li><a asp-action="BrowseCandidate" asp-controller="Candidate">Browse Candidate</a></li>

                                @{
                                    if (isSignedIn)
                                    {
                                        if (user.Type == "Employee")
                                        {
                                            <li class="active has-children">
                                                <a href="#">Employee</a>
                                                <ul>
                                                    <li><a asp-action="Dashboard" asp-controller="Employer">Dashboard</a></li>
                                                    <li><a asp-action="Profile" asp-controller="Employer">Profile</a></li>
                                                    <li><a asp-action="JobPost" asp-controller="JobPost">Post a Job</a></li>
                                                    <li><a asp-action="ManageJobs" asp-controller="JobPost">Manage Job</a></li>
                                                    <li><a asp-action="ManageRequest" asp-controller="Employer">Manage Requests</a></li>
                                                    <li><a asp-action="Message" asp-controller="ChatApp">Message</a></li>
                                                    <li><a asp-action="Logout" asp-controller="Account">Logout</a></li>
                                                </ul>
                                            </li>
                                        }
                                        if (user.Type == "Candidate")
                                        {
                                            <li class="active has-children">
                                                <a href="#">Candidate</a>
                                                <ul>
                                                    <li><a asp-action="Profile" asp-controller="Candidate">Profile</a></li>
                                                    <li><a asp-action="Message" asp-controller="ChatApp">Message</a></li>
                                                    <li><a href="#" @*asp-action="MyJob" asp-controller="Candidate"*@>MyJob</a></li>
                                                </ul>
                                            </li>
                                        }
                                    }
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="header-right-menu">

                        <ul>
                            @{
                                if (isSignedIn && user.Type == "Employee")
                                {
                                    <li><a asp-action="JobPost" asp-controller="JobPost" class="post-jobs">Post jobs</a></li>
                                }
                                else if(!isSignedIn)
                                {
                                    <li><a asp-action="JobPost" asp-controller="JobPost" class="post-jobs">Post jobs</a></li>
                                }
                                if (isSignedIn)
                                {
                                    
                                  <li><a asp-action="Logout" asp-controller="Account"><i class="fa fa-user"></i>Welcome @userName</a></li>
                                }
                                else
                                {
                                    <li><a asp-action="EmployeeSignUp" asp-controller="Account"><i class="fa fa-user"></i>sign up</a></li>
                                    <li><a asp-action="Login" asp-controller="Account"><i class="fa fa-lock"></i>login</a></li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

ImmigrationApp/Views/Shared/_headerwhite.cshtml
@{
    //Sign In Check
    var userName = "";
    var user = new User();
    var isSignedIn = SignInManager.IsSignedIn(User);
    if (isSignedIn)
    {
        var userId = _currentuser.GetUserId();
        user = await _db.User.SingleOrDefaultAsync(c => c.Id.Equals(userId));
        //
        userName = "" + user.FirstName.Substring(0, 1) + "" + user.LastName?.Substring(0, 1) + "";
    }
}
<!-- Header Area Start -->
<header class="jobguru-header-area stick-top forsticky page-header">
    <div class="menu-animation">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2">
                    <div class="site-logo">
                        <a asp-action="Index" asp-controller="Home">
                            <img src="/Front/assets/img/logo-2.png" alt="jobguru" />
                        </a>
                    </div>
                    <!-- Responsive Menu Start -->
                    <div class="jobguru-responsive-menu"></div>
                    <!-- Responsive Menu Start -->
                </div>
                <div class="col-lg-6">
                    <div class="header-menu">
                        <nav id="navigation">
                            <ul id="jobguru_navigation">
                                <li><a asp-action="JobFind" asp-controller="FindJob" asp-route-Alpha="ScokTCWcgLjzLxrUzuUbvHTbOchVBQFggmxnskcILSzqzzczAbKoHGFzdCKptziwbmPVlqHhKQfGlQBeWZOXMRLaXykViWmczdNzmkQlJqLhkgRrTsazHoZPsyVIejTq">Find Jobs</a></li>
                                <li><a asp-action="Companies" asp-controller="Home">Companies</a></li>
                                <li><a href="#">Salary Guide</a></li>
                                <li><a asp-action="BrowseCandidate" asp-controller="Candidate">Browse Candidate</a></li>

                                @{
                                    if (isSignedIn)
                                    {
                                        if (user.Type == "Employee")
                                        {
                                            <li class="active has-children">
                                                <a href="#">Employee</a>
                                                <ul>
                                                    <li><a asp-action="Dashboard" asp-controller="Employer">Dashboard</a></li>
                                                    <li><a asp-action="Profile" asp-controller="Employer">Profile</a></li>
                                                    <li><a asp-action="JobPost" asp-controller="JobPost">Post a Job</a></li>
                                                    <li><a asp-action="ManageJobs" asp-controller="JobPost">Manage Job</a></li>
                                                    <li><a asp-action="ManageRequest" asp-controller="Employer">Manage Requests</a></li>
                                                    <li><a asp-action="Message" asp-controller="ChatApp">Message</a></li>
                                                    <li><a asp-action="Logout" asp-controller="Account">Logout</a></li>
                                                </ul>
                                            </li>
                                        }
                                        if (user.Type == "Candidate")
                                        {
                                            <li class="active has-children">
                                                <a href="#">Candidate</a>
                                                <ul>
                                                    <li><a asp-action="Profile" asp-controller="Candidate">Profile</a></li>
                                                    <li><a asp-action="Message" asp-controller="ChatApp">Message</a></li>
                                                    <li><a href="#" @*asp-action="MyJob" asp-controller="Candidate"*@>MyJob</a></li>
                                                </ul>
                                            </li>
                                        }
                                    }
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="header-right-menu">
                        <ul>
                            @{
                                if (isSignedIn && user.Type == "Employee")
                                {
                                    <li><a asp-action="JobPost" asp-controller="JobPost" class="post-jobs">Post jobs</a></li>
                                }
                                else if (!isSignedIn)
                                {
                                    <li><a asp-action="JobPost" asp-controller="JobPost" class="post-jobs">Post jobs</a></li>
                                }
                                if (isSignedIn)
                                {

                                    <li><a asp-action="Logout" asp-controller="Account"><i class="fa fa-user"></i>Welcome @userName</a></li>
                                }
                                else
                                {
                                    <li><a asp-action="EmployeeSignUp" asp-controller="Account"><i class="fa fa-user"></i>sign up</a></li>
                                    <li><a asp-action="Login" asp-controller="Account"><i class="fa fa-lock"></i>login</a></li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header Area End -->